### ISSUE TITLE
Ruby 2.7 deprecation warnings

### ISSUE THREAD

**Issue by morgoth** [thhermansen/google_static_maps_helper#4]
When using the gem with Ruby 2.7, the deprecation is thrown:

```
/home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/google_static_maps_helper-1.3.5/lib/google_static_maps_helper/map.rb:58: warning: URI.escape is obsolete
/home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/google_static_maps_helper-1.3.5/lib/google_static_maps_helper/marker.rb:57: warning: URI.escape is obsolete
```

**Comment by thhermansen** [comment]
Hi, feel free to open a PR which fixes this :-)

**Comment by thhermansen** [comment]
Released a new version now: https://rubygems.org/gems/google_static_maps_helper

10 years since last release 🎉

![image](https://user-images.githubusercontent.com/92300/82549338-13857a80-9b5d-11ea-9f2f-f20caa421ed2.png)

**Comment by morgoth** [comment]
Thank you :-)
